import { fetchData } from "./api";
import type { CareerStats } from "../types";
import history from "../data/championsHistory.json";

// Titles and career wins/poles up to `throughSeason` are generated by
// scripts/generate-champions.mjs (jolpi has no cheap endpoint for either).
// Only the season in progress is added live, from the standings (which the
// Grid fetches anyway) plus one grid-1 results request. Re-run the script once a
// season, after the finale.
const titles = history as unknown as {
  drivers: Record<string, number[]>; // id -> championship years
  constructors: Record<string, number[]>;
  defending: { driver: string | null; constructor: string | null };
  throughSeason: number;
  career: Record<string, { wins: number; poles: number }>;
};

let pending: Promise<Record<string, CareerStats>> | null = null;

// Rejects on failure (nothing is cached), so a retry is just calling it again.
export const loadCareerStats = (): Promise<Record<string, CareerStats>> =>
  (pending ??= compute().catch((e) => {
    pending = null;
    throw e;
  }));

async function compute(): Promise<Record<string, CareerStats>> {
  const [dData, cData, gridData] = await Promise.all([
    fetchData("/current/driverStandings.json"),
    fetchData("/current/constructorStandings.json"),
    fetchData("/current/grid/1/results.json?limit=100"),
  ]);
  const live = parseInt(dData.StandingsTable.season, 10) > titles.throughSeason;

  // poles = grid-1 starts, same definition the generator uses (matches Wikipedia)
  const poles: Record<string, number> = {};
  if (live)
    for (const race of gridData.RaceTable.Races)
      for (const r of race.Results.filter((r: any) => r.grid === "1")) {
        poles[r.Driver.driverId] = (poles[r.Driver.driverId] || 0) + 1;
        poles[r.Constructor.constructorId] = (poles[r.Constructor.constructorId] || 0) + 1;
      }

  const stats: Record<string, CareerStats> = {};
  const add = (id: string, wins: string, kind: "drivers" | "constructors") => {
    const base = titles.career[id] ?? { wins: 0, poles: 0 }; // not in the baseline = rookie
    stats[id] = {
      wins: base.wins + (live ? parseInt(wins, 10) : 0),
      poles: base.poles + (poles[id] || 0),
      titleYears: titles[kind][id] ?? [],
      defending:
        id === (kind === "drivers" ? titles.defending.driver : titles.defending.constructor),
    };
  };
  for (const d of dData.StandingsTable.StandingsLists[0]?.DriverStandings ?? [])
    add(d.Driver.driverId, d.wins, "drivers");
  for (const c of cData.StandingsTable.StandingsLists[0]?.ConstructorStandings ?? [])
    add(c.Constructor.constructorId, c.wins, "constructors");
  return stats;
}
