export const getTeamHex = (constructorId: string): string => {
  const colors: Record<string, string> = {
    red_bull: "#3671C6",
    ferrari: "#E80020",
    mercedes: "#27F4D2",
    mclaren: "#FF8000",
    aston_martin: "#229971",
    alpine: "#0093CC",
    williams: "#64C4FF",
    rb: "#6692FF",
    kick_sauber: "#52E252",
    haas: "#B6BABD",
    alphatauri: "#041F3D",
    alpha_tauri: "#041F3D",
    alfa: "#C92D4B",
    racing_point: "#F596C8",
    renault: "#FFF500",
    toro_rosso: "#469BFF",
    force_india: "#F596C8",
    manor: "#323232",
    marussia: "#6E0000",
    caterham: "#005030",
    lotus_f1: "#E5C253",
    lotus_racing: "#004225",
    hrt: "#A6904F",
    virgin: "#CF2220",
    brawn: "#B8FD6E",
    bmw_sauber: "#FFFFFF",
    toyota: "#E31D2B",
    super_aguri: "#DA3638",
    spyker: "#FF7F00",
    honda: "#CD0000",
    midland: "#808080",
    bar: "#FFFFFF",
    jordan: "#FFEC00",
    minardi: "#000000",
    jaguar: "#004225",
    arrows: "#FFA500",
    prost: "#0000FF",
    benetton: "#7FBCFF",
    sauber: "#006EFF",
    tyrrell: "#0000FF",
    stewart: "#FFFFFF",
    ligier: "#2635C7",
    footwork: "#D63445",
    larrousse: "#224A64",
    brabham: "#1A2556",
    march: "#C4282D",
    simtek: "#4D2D7D",
    lola: "#D22129",
    pacific: "#D8205C",
    forti: "#F9E434",
    leyton_house: "#88D6C8",
    zakspeed: "#D63445",
    onyx: "#3C63A6",
    brm: "#004225",
    cooper: "#004225",
    vanwall: "#004225",
    maserati: "#CE212C",
    matra: "#0000FF",
    lotus: "#E5C253",
    shadow: "#000000",
    wolf: "#BE9F55",
    penske: "#D22129",
    hesketh: "#FFFFFF",
    surtees: "#FFFF00",
    dallara: "#D22129",
    fondmetal: "#2D2D2D",
    mercedes_benz: "#C0C0C0",
  };
  return colors[constructorId] || "#525252";
};

export const getTeamLogo = (constructorId: string): string | null => {
  const slugMap: Record<string, string> = {
    red_bull: "red-bull-racing",
    ferrari: "ferrari",
    mercedes: "mercedes",
    mclaren: "mclaren",
    aston_martin: "aston-martin",
    alpine: "alpine",
    williams: "williams",
    rb: "rb",
    kick_sauber: "kick-sauber",
    haas: "haas-f1-team",
  };
  if (slugMap[constructorId]) {
    return `https://media.formula1.com/content/dam/fom-website/teams/2025/${slugMap[constructorId]}-logo.png.transform/2col/image.png`;
  }
  return null;
};

export const getCircuitData = (
  circuitId: string
): { img: string; record: string; mostWins: string } => {
  const data: Record<string, { img: string; record: string; mostWins: string }> =
    {
      bahrain: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png",
        record: "1:31.447 (Pedro de la Rosa, 2005)",
        mostWins: "Lewis Hamilton (5)",
      },
      jeddah: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png",
        record: "1:30.734 (Lewis Hamilton, 2021)",
        mostWins: "Max Verstappen (2), Oscar Piastri (2)",
      },
      albert_park: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png",
        record: "1:19.813 (Charles Leclerc, 2024)",
        mostWins: "Michael Schumacher (4)",
      },
      suzuka: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Japan_Circuit.png",
        record: "1:30.965 (Kimi Antonelli, 2025)",
        mostWins: "Michael Schumacher (6)",
      },
      shanghai: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit.png",
        record: "1:32.238 (Michael Schumacher, 2004)",
        mostWins: "Lewis Hamilton (6)",
      },
      miami: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png",
        record: "1:29.708 (Max Verstappen, 2023)",
        mostWins: "Max Verstappen (2), Oscar Piastri (2)",
      },
      imola: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Emilia_Romagna_Circuit.png",
        record: "1:15.484 (Lewis Hamilton, 2020)",
        mostWins: "Michael Schumacher (7)",
      },
      monaco: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit.png",
        record: "1:12.909 (Lewis Hamilton, 2021)",
        mostWins: "Ayrton Senna (6)",
      },
      villeneuve: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit.png",
        record: "1:13.078 (Valtteri Bottas, 2019)",
        mostWins: "Michael Schumacher (7), Lewis Hamilton (7)",
      },
      catalunya: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png",
        record: "1:15.743 (Oscar Piastri, 2025)",
        mostWins: "Michael Schumacher (6), Lewis Hamilton (6)",
      },
      red_bull_ring: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Austria_Circuit.png",
        record: "1:07.924 (Oscar Piastri, 2025)",
        mostWins: "Max Verstappen (5)",
      },
      silverstone: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png",
        record: "1:27.097 (Max Verstappen, 2020)",
        mostWins: "Lewis Hamilton (9)",
      },
      hungaroring: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png",
        record: "1:16.627 (Lewis Hamilton, 2020)",
        mostWins: "Lewis Hamilton (8)",
      },
      spa: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png",
        record: "1:44.701 (Sergio Pérez, 2024)",
        mostWins: "Michael Schumacher (6)",
      },
      zandvoort: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png",
        record: "1:11.097 (Lewis Hamilton, 2021)",
        mostWins: "Jim Clark (4)",
      },
      monza: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png",
        record: "1:20.901 (Lando Norris, 2025)",
        mostWins: "Michael Schumacher (5), Lewis Hamilton (5)",
      },
      baku: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Azerbaijan_Circuit.png",
        record: "1:43.009 (Charles Leclerc, 2019)",
        mostWins: "Sergio Perez (2), Max Verstappen (2)",
      },
      marina_bay: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit.png",
        record: "1:33.808 (Lewis Hamilton, 2025)",
        mostWins: "Sebastian Vettel (5)",
      },
      americas: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png",
        record: "1:36.169 (Charles Leclerc, 2019)",
        mostWins: "Lewis Hamilton (5)",
      },
      rodriguez: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png",
        record: "1:17.774 (Valtteri Bottas, 2021)",
        mostWins: "Max Verstappen (5)",
      },
      interlagos: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png",
        record: "1:10.540 (Valtteri Bottas, 2018)",
        mostWins: "Alain Prost (6)",
      },
      vegas: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1699544976/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit.png",
        record: "1:33.365 (Max Verstappen, 2025)",
        mostWins: "Max Verstappen (2)",
      },
      losail: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Qatar_Circuit.png",
        record: "1:22.996 (Oscar Piastri, 2025)",
        mostWins: "Lewis Hamilton (1), Max Verstappen (2)",
      },
      yas_marina: {
        img: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png",
        record: "1:26.725 (Charles Leclerc, 2025)",
        mostWins: "Lewis Hamilton (5), Max Verstappen (6)",
      },
    };
  return data[circuitId] || { img: "", record: "N/A", mostWins: "N/A" };
};

export const getCountryCode = (name: string): string | null => {
  const map: Record<string, string> = {
    British: "gb",
    UK: "gb",
    "United Kingdom": "gb",
    "Great Britain": "gb",
    Dutch: "nl",
    Netherlands: "nl",
    Monegasque: "mc",
    Monaco: "mc",
    Spanish: "es",
    Spain: "es",
    Mexican: "mx",
    Mexico: "mx",
    Australian: "au",
    Australia: "au",
    German: "de",
    Germany: "de",
    French: "fr",
    France: "fr",
    Finnish: "fi",
    Finland: "fi",
    Canadian: "ca",
    Canada: "ca",
    Japanese: "jp",
    Japan: "jp",
    Chinese: "cn",
    China: "cn",
    Thai: "th",
    Thailand: "th",
    Danish: "dk",
    Denmark: "dk",
    American: "us",
    USA: "us",
    "United States": "us",
    Italian: "it",
    Italy: "it",
    Brazilian: "br",
    Brazil: "br",
    Austrian: "at",
    Austria: "at",
    Swiss: "ch",
    Switzerland: "ch",
    Belgian: "be",
    Belgium: "be",
    Hungarian: "hu",
    Hungary: "hu",
    "Saudi Arabian": "sa",
    "Saudi Arabia": "sa",
    Emirati: "ae",
    UAE: "ae",
    "Abu Dhabi": "ae",
    Azerbaijani: "az",
    Azerbaijan: "az",
    Singaporean: "sg",
    Singapore: "sg",
    Qatari: "qa",
    Qatar: "qa",
    Bahraini: "bh",
    Bahrain: "bh",
    Portuguese: "pt",
    Portugal: "pt",
    Turkish: "tr",
    Turkey: "tr",
    Russian: "ru",
    Russia: "ru",
    Polish: "pl",
    Poland: "pl",
    Swedish: "se",
    Sweden: "se",
    "New Zealander": "nz",
    "New Zealand": "nz",
    Argentine: "ar",
    Argentina: "ar",
    Venezuelan: "ve",
    Venezuela: "ve",
    Colombian: "co",
    Colombia: "co",
    Indian: "in",
    India: "in",
    Indonesian: "id",
    Indonesia: "id",
    Malaysian: "my",
    Malaysia: "my",
    Korean: "kr",
    Korea: "kr",
    "South African": "za",
    "South Africa": "za",
  };
  return map[name] || null;
};

export const formatDateLocal = (dateStr: string, timeStr: string): string => {
  if (!dateStr || !timeStr) return "TBA";
  const isoString = `${dateStr}T${timeStr}${timeStr.endsWith("Z") ? "" : "Z"}`;
  const date = new Date(isoString);
  if (isNaN(date.getTime())) return "TBA";
  return new Intl.DateTimeFormat("en-US", {
    weekday: "short",
    hour: "numeric",
    minute: "2-digit",
    hour12: false,
  }).format(date);
};
